/**
 * Tool metadata. This module is deliberately free of browser APIs and heavy
 * imports so it can be read on the server (metadata, sitemap, generated copy)
 * and in the browser (workspace UI) without pulling in pdf-lib or pdf.js.
 *
 * Execution lives in `runners.ts`, which is only ever imported from the client.
 */
import type { ToolDefinition, ToolId } from "./types";

const PDF_ACCEPT = "application/pdf,.pdf";

export const TOOLS: Record<ToolId, ToolDefinition> = {
  "merge-pdf": {
    id: "merge-pdf",
    slug: "merge-pdf",
    name: "Merge PDF",
    verb: "merge",
    outputNoun: "merged PDF",
    actionLabel: "Merge PDFs",
    tagline: "Combine several PDF files into one document, in the order you choose.",
    blurb: "Combine PDFs into one file, in your order.",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF",
    extensions: [".pdf"],
    multiple: true,
    minFiles: 2,
    maxFiles: 30,
    maxFileSizeMB: 100,
    fileListControls: { reorder: true, rotate: true, remove: true },
    outputKind: "pdf",
    available: true,
    keywords: ["merge pdf", "combine pdf", "pdf merger", "join pdf files"],
    related: ["split-pdf", "compress-pdf", "rotate-pdf", "jpg-to-pdf"],
  },

  "split-pdf": {
    id: "split-pdf",
    slug: "split-pdf",
    name: "Split PDF",
    verb: "split",
    outputNoun: "split PDF files",
    actionLabel: "Split PDF",
    tagline: "Break one PDF into separate files, or pull out just the pages you need.",
    blurb: "Split a PDF or extract just the pages you need.",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF",
    extensions: [".pdf"],
    multiple: false,
    minFiles: 1,
    maxFiles: 1,
    maxFileSizeMB: 100,
    options: [
      {
        key: "mode",
        label: "How should we split it?",
        type: "radio",
        defaultValue: "each",
        choices: [
          { label: "One PDF per page", value: "each" },
          { label: "Extract a page range", value: "range" },
        ],
      },
      {
        key: "ranges",
        label: "Pages to extract",
        type: "text",
        defaultValue: "1-3",
        placeholder: "e.g. 1-3, 7, 9-12",
        help: "Only used when extracting a range. Page numbers start at 1.",
      },
    ],
    outputKind: "pdf",
    available: true,
    keywords: ["split pdf", "extract pdf pages", "separate pdf pages", "pdf splitter"],
    related: ["merge-pdf", "rotate-pdf", "compress-pdf", "pdf-to-jpg"],
  },

  "compress-pdf": {
    id: "compress-pdf",
    slug: "compress-pdf",
    name: "Compress PDF",
    verb: "compress",
    outputNoun: "compressed PDF",
    actionLabel: "Compress PDF",
    tagline: "Shrink a PDF so it fits an upload limit or an email attachment.",
    blurb: "Shrink a PDF to fit an upload or email limit.",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF",
    extensions: [".pdf"],
    multiple: false,
    minFiles: 1,
    maxFiles: 1,
    maxFileSizeMB: 150,
    options: [
      {
        key: "level",
        label: "Compression level",
        type: "radio",
        defaultValue: "balanced",
        choices: [
          { label: "Lossless — structure only, pages untouched", value: "lossless" },
          { label: "Balanced — good quality, much smaller", value: "balanced" },
          { label: "Strong — smallest file", value: "strong" },
          { label: "Target size — keep trying until it fits", value: "target" },
        ],
      },
      {
        key: "targetKB",
        label: "Target size (KB)",
        type: "number",
        defaultValue: 1024,
        min: 50,
        max: 20480,
        step: 50,
        help: "Only used with the target size level. 1024 KB is roughly 1 MB.",
      },
    ],
    outputKind: "pdf",
    available: true,
    keywords: ["compress pdf", "reduce pdf size", "shrink pdf", "pdf compressor"],
    related: ["merge-pdf", "split-pdf", "pdf-to-jpg", "rotate-pdf"],
  },

  "rotate-pdf": {
    id: "rotate-pdf",
    slug: "rotate-pdf",
    name: "Rotate PDF",
    verb: "rotate",
    outputNoun: "rotated PDF",
    actionLabel: "Rotate PDF",
    tagline: "Turn sideways or upside-down pages the right way up and save the change.",
    blurb: "Fix sideways pages and save the change.",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF",
    extensions: [".pdf"],
    multiple: false,
    minFiles: 1,
    maxFiles: 1,
    maxFileSizeMB: 100,
    options: [
      {
        key: "angle",
        label: "Rotation",
        type: "radio",
        defaultValue: 90,
        choices: [
          { label: "90° clockwise", value: 90 },
          { label: "180°", value: 180 },
          { label: "270° (90° anticlockwise)", value: 270 },
        ],
      },
      {
        key: "pages",
        label: "Pages to rotate",
        type: "text",
        defaultValue: "",
        placeholder: "Leave empty for all pages",
        help: "Accepts a list like 2, 5-8. Leave it blank to rotate the whole document.",
      },
    ],
    outputKind: "pdf",
    available: true,
    keywords: ["rotate pdf", "turn pdf pages", "fix sideways pdf", "rotate pdf permanently"],
    related: ["merge-pdf", "split-pdf", "edit-pdf", "compress-pdf"],
  },

  watermark: {
    id: "watermark",
    slug: "watermark",
    name: "Watermark PDF",
    verb: "watermark",
    outputNoun: "watermarked PDF",
    actionLabel: "Add watermark",
    tagline: "Stamp text such as DRAFT or CONFIDENTIAL across every page.",
    blurb: "Stamp text across every page of a PDF.",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF",
    extensions: [".pdf"],
    multiple: false,
    minFiles: 1,
    maxFiles: 1,
    maxFileSizeMB: 100,
    options: [
      {
        key: "text",
        label: "Watermark text",
        type: "text",
        defaultValue: "DRAFT",
        placeholder: "e.g. CONFIDENTIAL",
        required: true,
      },
      {
        key: "position",
        label: "Placement",
        type: "select",
        defaultValue: "diagonal",
        choices: [
          { label: "Diagonal across the page", value: "diagonal" },
          { label: "Centred", value: "center" },
          { label: "Bottom right", value: "bottom-right" },
          { label: "Top left", value: "top-left" },
        ],
      },
      {
        key: "fontSize",
        label: "Text size",
        type: "number",
        defaultValue: 48,
        min: 8,
        max: 144,
        step: 2,
      },
      {
        key: "opacity",
        label: "Opacity",
        type: "number",
        defaultValue: 0.3,
        min: 0.05,
        max: 1,
        step: 0.05,
        help: "0.05 is barely visible, 1 is solid.",
      },
    ],
    outputKind: "pdf",
    available: true,
    keywords: ["watermark pdf", "add watermark to pdf", "stamp pdf", "confidential pdf"],
    related: ["sign-pdf", "edit-pdf", "merge-pdf", "compress-pdf"],
  },

  "sign-pdf": {
    id: "sign-pdf",
    slug: "sign-pdf",
    name: "Sign PDF",
    verb: "sign",
    outputNoun: "signed PDF",
    actionLabel: "Sign PDF",
    tagline: "Add a typed signature to a document and download it straight away.",
    blurb: "Add a typed signature to a document.",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF",
    extensions: [".pdf"],
    multiple: false,
    minFiles: 1,
    maxFiles: 1,
    maxFileSizeMB: 100,
    options: [
      {
        key: "text",
        label: "Your signature",
        type: "text",
        defaultValue: "",
        placeholder: "Type your full name",
        required: true,
      },
      {
        key: "pageNumber",
        label: "Page",
        type: "number",
        defaultValue: 0,
        min: 0,
        max: 9999,
        step: 1,
        help: "Leave at 0 to sign the last page.",
      },
      {
        key: "fontSize",
        label: "Signature size",
        type: "number",
        defaultValue: 16,
        min: 8,
        max: 48,
        step: 1,
      },
    ],
    outputKind: "pdf",
    available: true,
    keywords: ["sign pdf", "e-sign pdf", "electronic signature pdf", "add signature to pdf"],
    related: ["watermark", "edit-pdf", "merge-pdf", "compress-pdf"],
  },

  "edit-pdf": {
    id: "edit-pdf",
    slug: "edit-pdf",
    name: "Edit PDF",
    verb: "edit",
    outputNoun: "edited PDF",
    actionLabel: "Add text",
    tagline: "Drop text onto any page of an existing PDF and save a new copy.",
    blurb: "Add text anywhere on a PDF page.",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF",
    extensions: [".pdf"],
    multiple: false,
    minFiles: 1,
    maxFiles: 1,
    maxFileSizeMB: 100,
    options: [
      {
        key: "text",
        label: "Text to add",
        type: "text",
        defaultValue: "",
        placeholder: "Type the text you want on the page",
        required: true,
      },
      { key: "pageNumber", label: "Page number", type: "number", defaultValue: 1, min: 1, step: 1 },
      { key: "fontSize", label: "Font size", type: "number", defaultValue: 12, min: 6, max: 72, step: 1 },
      { key: "x", label: "Distance from the left (pt)", type: "number", defaultValue: 50, min: 0, step: 5 },
      { key: "y", label: "Distance from the top (pt)", type: "number", defaultValue: 100, min: 0, step: 5 },
    ],
    outputKind: "pdf",
    available: true,
    keywords: ["edit pdf", "add text to pdf", "pdf editor", "annotate pdf"],
    related: ["sign-pdf", "watermark", "rotate-pdf", "merge-pdf"],
  },

  "pdf-to-jpg": {
    id: "pdf-to-jpg",
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    verb: "convert",
    outputNoun: "JPG images",
    actionLabel: "Convert to JPG",
    tagline: "Turn every page of a PDF into a JPG image you can download.",
    blurb: "Turn every PDF page into a JPG image.",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF",
    extensions: [".pdf"],
    multiple: false,
    minFiles: 1,
    maxFiles: 1,
    maxFileSizeMB: 100,
    options: [
      {
        key: "scale",
        label: "Image resolution",
        type: "radio",
        defaultValue: 2,
        choices: [
          { label: "Screen — 72 dpi", value: 1 },
          { label: "High — 144 dpi", value: 2 },
          { label: "Print — 288 dpi", value: 4 },
        ],
      },
      {
        key: "quality",
        label: "JPG quality",
        type: "number",
        defaultValue: 0.92,
        min: 0.4,
        max: 1,
        step: 0.02,
      },
    ],
    outputKind: "images",
    available: true,
    keywords: ["pdf to jpg", "convert pdf to image", "pdf to jpeg", "pdf page to picture"],
    related: ["pdf-to-image", "jpg-to-pdf", "compress-pdf", "split-pdf"],
  },

  "pdf-to-image": {
    id: "pdf-to-image",
    slug: "pdf-to-image",
    name: "PDF to PNG",
    verb: "convert",
    outputNoun: "PNG images",
    actionLabel: "Convert to PNG",
    tagline: "Export PDF pages as lossless PNG images with a transparent-safe white background.",
    blurb: "Export PDF pages as lossless PNG images.",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF",
    extensions: [".pdf"],
    multiple: false,
    minFiles: 1,
    maxFiles: 1,
    maxFileSizeMB: 100,
    options: [
      {
        key: "scale",
        label: "Image resolution",
        type: "radio",
        defaultValue: 2,
        choices: [
          { label: "Screen — 72 dpi", value: 1 },
          { label: "High — 144 dpi", value: 2 },
          { label: "Print — 288 dpi", value: 4 },
        ],
      },
    ],
    outputKind: "images",
    available: true,
    keywords: ["pdf to png", "pdf to image", "export pdf pages as images", "pdf to picture"],
    related: ["pdf-to-jpg", "jpg-to-pdf", "split-pdf", "compress-pdf"],
  },

  "jpg-to-pdf": {
    id: "jpg-to-pdf",
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    verb: "convert",
    outputNoun: "PDF",
    actionLabel: "Create PDF",
    tagline: "Combine JPG or PNG images into a single PDF, one image per page.",
    blurb: "Combine JPG or PNG images into one PDF.",
    accept: "image/jpeg,image/png,.jpg,.jpeg,.png",
    acceptLabel: "JPG or PNG",
    extensions: [".jpg", ".jpeg", ".png"],
    multiple: true,
    minFiles: 1,
    maxFiles: 60,
    maxFileSizeMB: 40,
    fileListControls: { reorder: true, remove: true },
    options: [
      {
        key: "pageSize",
        label: "Page size",
        type: "radio",
        defaultValue: "fit",
        choices: [
          { label: "A4 pages with margins", value: "fit" },
          { label: "Page matches the image exactly", value: "match" },
        ],
      },
      {
        key: "orientation",
        label: "Orientation",
        type: "select",
        defaultValue: "auto",
        choices: [
          { label: "Match each image", value: "auto" },
          { label: "Portrait", value: "portrait" },
          { label: "Landscape", value: "landscape" },
        ],
      },
      {
        key: "marginPt",
        label: "Margin (pt)",
        type: "number",
        defaultValue: 24,
        min: 0,
        max: 120,
        step: 4,
      },
    ],
    outputKind: "pdf",
    available: true,
    keywords: ["jpg to pdf", "image to pdf", "png to pdf", "photos to pdf"],
    related: ["pdf-to-jpg", "merge-pdf", "compress-pdf", "pdf-to-image"],
  },

  "pdf-to-word": {
    id: "pdf-to-word",
    slug: "pdf-to-word",
    name: "PDF to Word",
    verb: "convert",
    outputNoun: "Word document",
    actionLabel: "Convert to Word",
    tagline: "Turn a PDF into an editable DOCX file you can open in Word or Google Docs.",
    blurb: "Turn a PDF into an editable DOCX file.",
    accept: PDF_ACCEPT,
    acceptLabel: "PDF",
    extensions: [".pdf"],
    multiple: false,
    minFiles: 1,
    maxFiles: 1,
    maxFileSizeMB: 25,
    outputKind: "pdf",
    serverSide: true,
    available: true,
    keywords: ["pdf to word", "pdf to docx", "convert pdf to editable word", "pdf to doc"],
    related: ["word-to-pdf", "pdf-to-jpg", "compress-pdf", "merge-pdf"],
  },

  "word-to-pdf": {
    id: "word-to-pdf",
    slug: "word-to-pdf",
    name: "Word to PDF",
    verb: "convert",
    outputNoun: "PDF",
    actionLabel: "Convert to PDF",
    tagline: "Turn a DOCX file into a paginated PDF that looks the same everywhere.",
    blurb: "Turn a DOCX into a paginated PDF.",
    accept:
      ".doc,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    acceptLabel: "DOC or DOCX",
    extensions: [".doc", ".docx"],
    multiple: false,
    minFiles: 1,
    maxFiles: 1,
    maxFileSizeMB: 40,
    outputKind: "pdf",
    available: true,
    keywords: ["word to pdf", "docx to pdf", "convert doc to pdf", "save word as pdf"],
    related: ["pdf-to-word", "excel-to-pdf", "merge-pdf", "compress-pdf"],
  },

  "excel-to-pdf": {
    id: "excel-to-pdf",
    slug: "excel-to-pdf",
    name: "Excel to PDF",
    verb: "convert",
    outputNoun: "PDF",
    actionLabel: "Convert to PDF",
    tagline: "Lay out spreadsheet data as a clean, readable PDF table.",
    blurb: "Lay out spreadsheet data as a PDF table.",
    accept:
      ".xls,.xlsx,.csv,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    acceptLabel: "XLS, XLSX or CSV",
    extensions: [".xls", ".xlsx", ".csv"],
    multiple: false,
    minFiles: 1,
    maxFiles: 1,
    maxFileSizeMB: 40,
    options: [
      {
        key: "sheets",
        label: "Sheets to include",
        type: "radio",
        defaultValue: "all",
        choices: [
          { label: "Every sheet in the workbook", value: "all" },
          { label: "First sheet only", value: "first" },
        ],
      },
      {
        key: "orientation",
        label: "Page orientation",
        type: "select",
        defaultValue: "landscape",
        choices: [
          { label: "Landscape — better for wide tables", value: "landscape" },
          { label: "Portrait", value: "portrait" },
        ],
      },
    ],
    outputKind: "pdf",
    available: true,
    keywords: ["excel to pdf", "xlsx to pdf", "spreadsheet to pdf", "csv to pdf"],
    related: ["word-to-pdf", "pdf-to-word", "merge-pdf", "compress-pdf"],
  },
};

export const TOOL_IDS = Object.keys(TOOLS) as ToolId[];

/** Tools that actually work today — the only ones that get landing pages. */
export const AVAILABLE_TOOL_IDS = TOOL_IDS.filter((id) => TOOLS[id].available);

export function getTool(id: ToolId): ToolDefinition {
  return TOOLS[id];
}

export function findToolBySlug(slug: string): ToolDefinition | undefined {
  return TOOL_IDS.map((id) => TOOLS[id]).find((tool) => tool.slug === slug);
}

/** Default option values for a tool, used to seed the workspace form. */
export function defaultOptions(tool: ToolDefinition): Record<string, string | number> {
  const values: Record<string, string | number> = {};
  for (const field of tool.options ?? []) values[field.key] = field.defaultValue;
  return values;
}
